"""Initial revision

Revision ID: 0a34f8a05e9b
Revises: f2fe6f1c2ab2
Create Date: 2025-02-21 01:20:15.138951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a34f8a05e9b'
down_revision: Union[str, None] = 'f2fe6f1c2ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
