"""Initial revision

Revision ID: 2513672e51f5
Revises: 0a34f8a05e9b
Create Date: 2025-02-21 01:44:25.171346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2513672e51f5'
down_revision: Union[str, None] = '0a34f8a05e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('patients_user_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_user_id_fkey', 'patients', 'users', ['user_id'], ['_id'])
    op.alter_column('patients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
