"""Initial revision

Revision ID: 5306bed5eb99
Revises: c584a435c10a
Create Date: 2025-02-22 23:17:33.409712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5306bed5eb99'
down_revision: Union[str, None] = 'c584a435c10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_user_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('doctor_leaves_doctor_id_fkey', 'doctor_leaves', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_leaves', 'doctors', ['doctor_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('doctors_user_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('medical_cards_patient_id_fkey', 'medical_cards', type_='foreignkey')
    op.drop_constraint('medical_cards_doctor_id_fkey', 'medical_cards', type_='foreignkey')
    op.create_foreign_key(None, 'medical_cards', 'patients', ['patient_id'], ['_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_cards', 'doctors', ['doctor_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('talons_doctor_id_fkey', 'talons', type_='foreignkey')
    op.drop_constraint('talons_patient_id_fkey', 'talons', type_='foreignkey')
    op.create_foreign_key(None, 'talons', 'patients', ['patient_id'], ['_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'talons', 'doctors', ['doctor_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'talons', type_='foreignkey')
    op.drop_constraint(None, 'talons', type_='foreignkey')
    op.create_foreign_key('talons_patient_id_fkey', 'talons', 'patients', ['patient_id'], ['_id'])
    op.create_foreign_key('talons_doctor_id_fkey', 'talons', 'doctors', ['doctor_id'], ['_id'])
    op.drop_constraint(None, 'medical_cards', type_='foreignkey')
    op.drop_constraint(None, 'medical_cards', type_='foreignkey')
    op.create_foreign_key('medical_cards_doctor_id_fkey', 'medical_cards', 'doctors', ['doctor_id'], ['_id'])
    op.create_foreign_key('medical_cards_patient_id_fkey', 'medical_cards', 'patients', ['patient_id'], ['_id'])
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_user_id_fkey', 'doctors', 'users', ['user_id'], ['_id'])
    op.drop_constraint(None, 'doctor_leaves', type_='foreignkey')
    op.create_foreign_key('doctor_leaves_doctor_id_fkey', 'doctor_leaves', 'doctors', ['doctor_id'], ['_id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_user_id_fkey', 'chat_messages', 'users', ['user_id'], ['_id'])
    # ### end Alembic commands ###
