"""Initial revision

Revision ID: 7080b061ff0e
Revises: 5306bed5eb99
Create Date: 2025-03-04 23:31:53.616052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7080b061ff0e'
down_revision: Union[str, None] = '5306bed5eb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.drop_constraint('chat_messages_user_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'doctors', ['doctor_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_user_id_fkey', 'chat_messages', 'users', ['user_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'doctor_id')
    op.alter_column('addresses', 'flat_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
