"""Initial revision

Revision ID: f2fe6f1c2ab2
Revises: 8229ccb24a91
Create Date: 2025-02-18 14:29:15.665051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fe6f1c2ab2'
down_revision: Union[str, None] = '8229ccb24a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_leaves', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctor_leaves', 'doctors', ['doctor_id'], ['_id'])
    op.add_column('doctors', sa.Column('education_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctors', 'education', ['education_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'education_id')
    op.drop_constraint(None, 'doctor_leaves', type_='foreignkey')
    op.drop_column('doctor_leaves', 'doctor_id')
    # ### end Alembic commands ###
